// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ReaderController from "./reader_controller"
application.register("reader", ReaderController)

import LoadingButtonController from "./loading_button_controller"
application.register("loading-button", LoadingButtonController)

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import ToggleButtonController from "./toggle_button_controller"
application.register("toggle-button", ToggleButtonController)

import AutoSubmitController from "./auto_submit_controller"
application.register("auto-submit", AutoSubmitController)

import MultiSelectController from "./multi_select_controller"
application.register("multi-select", MultiSelectController)

import DrawerController from "./drawer_controller"
application.register("drawer", DrawerController)

import DialogController from "./dialog_controller"
application.register("dialog", DialogController)

import ChapterFilterController from "./chapter_filter_controller"
application.register("chapter-filter", ChapterFilterController)

import RedirectSelectController from "./redirect_select_controller"
application.register("redirect-select", RedirectSelectController)

import FlashDismissController from "./flash_dismiss_controller"
application.register("flash-dismiss", FlashDismissController)

import TextExpandController from "./text_expand_controller"
application.register("text-expand", TextExpandController)

import ToastController from "./toast_controller"
application.register("toast", ToastController)

import BulkSelectController from "./bulk_select_controller"
application.register("bulk-select", BulkSelectController)

import LazyFrameController from "./lazy_frame_controller"
application.register("lazy-frame", LazyFrameController)

import SelectionToggleController from "./selection_toggle_controller"
application.register("selection-toggle", SelectionToggleController)

import OfflineCacheController from "./offline_cache_controller"
application.register("offline-cache", OfflineCacheController)

import OfflineLibraryController from "./offline_library_controller"
application.register("offline-library", OfflineLibraryController)

// ─── Custom Action Options ──────────────────────────────────────────────────
// Inline replacements for stimulus-fx. Uses Stimulus's first-party
// registerActionOption API -- no external dependency needed.

// :throttled -- limits how often an action fires.
// Usage: data-action="input->chapter-filter#filter:throttled"
// Set interval: data-throttled-wait="300" (default 300ms)
const throttleTimers = new WeakMap<Element, number>()
application.registerActionOption("throttled", ({ element }: { element: Element }) => {
  const wait = parseInt((element as HTMLElement).dataset.throttledWait || "300")
  if (throttleTimers.has(element)) return false
  throttleTimers.set(element, window.setTimeout(() => throttleTimers.delete(element), wait))
  return true
})

// :whenOutside -- fires only when event target is outside the controller element.
// Usage: data-action="click@window->dropdown#close:whenOutside"
application.registerActionOption("whenOutside", ({ event, element }: { event: Event; element: Element }) => {
  return !element.contains(event.target as Node)
})
