// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ReaderController from "./reader_controller"
application.register("reader", ReaderController)

import LoadingButtonController from "./loading_button_controller"
application.register("loading-button", LoadingButtonController)

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import ToggleButtonController from "./toggle_button_controller"
application.register("toggle-button", ToggleButtonController)

import AutoSubmitController from "./auto_submit_controller"
application.register("auto-submit", AutoSubmitController)
