// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ReaderController from "./reader_controller"
application.register("reader", ReaderController)

import LoadingButtonController from "./loading_button_controller"
application.register("loading-button", LoadingButtonController)

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import ToggleButtonController from "./toggle_button_controller"
application.register("toggle-button", ToggleButtonController)

import AutoSubmitController from "./auto_submit_controller"
application.register("auto-submit", AutoSubmitController)

import MultiSelectController from "./multi_select_controller"
application.register("multi-select", MultiSelectController)

import DrawerController from "./drawer_controller"
application.register("drawer", DrawerController)

import ChapterFilterController from "./chapter_filter_controller"
application.register("chapter-filter", ChapterFilterController)

import RedirectSelectController from "./redirect_select_controller"
application.register("redirect-select", RedirectSelectController)
