development:
  adapter: redis
  url: <%= ENV.fetch("ACTION_CABLE_REDIS_URL", "redis://127.0.0.1:6379/2") %>
  channel_prefix: scanarr_development

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("ACTION_CABLE_REDIS_URL", "redis://127.0.0.1:6379/2") %>
  channel_prefix: scanarr_production
