---
:concurrency: <%= ENV.fetch("SIDEKIQ_CONCURRENCY", 5) %>
:timeout: 25
:queues:
  - [default, 1]

development:
  :concurrency: <%= ENV.fetch("SIDEKIQ_CONCURRENCY", 3) %>

production:
  :concurrency: <%= ENV.fetch("SIDEKIQ_CONCURRENCY", 5) %>
