require "active_support/core_ext/integer/time"

Rails.application.configure do
  # Settings specified here will take precedence over those in config/application.rb.

  # Make code changes take effect immediately without server restart.
  config.enable_reloading = true

  # Do not eager load code on boot.
  config.eager_load = false

  # Show full error reports.
  config.consider_all_requests_local = true

  # Enable server timing.
  config.server_timing = true

  # Enable/disable Action Controller caching. By default Action Controller caching is disabled.
  # Run rails dev:cache to toggle Action Controller caching.
  if Rails.root.join("tmp/caching-dev.txt").exist?
    config.public_file_server.headers = { "cache-control" => "public, max-age=#{2.days.to_i}" }
  else
    config.action_controller.perform_caching = false
  end

  # Use Redis cache store so development behaves closer to production.
  config.cache_store = :redis_cache_store, {
    url: ENV.fetch("REDIS_URL", "redis://127.0.0.1:6379/0"),
    namespace: ENV.fetch("REDIS_CACHE_NAMESPACE", "scanarr:cache:development")
  }

  # Store uploaded files through Active Storage. Use ACTIVE_STORAGE_SERVICE=s3
  # with S3_* env vars for AWS S3, Cloudflare R2, MinIO, or another S3-compatible service.
  config.active_storage.service = ENV.fetch("ACTIVE_STORAGE_SERVICE", "local").to_sym

  # Serve files directly (proxy) instead of redirecting, saving an HTTP roundtrip per image.
  config.active_storage.resolve_model_to_route = :rails_storage_proxy

  # Don't actually send emails in development
  config.action_mailer.delivery_method = :test
  config.action_mailer.perform_deliveries = false
  config.action_mailer.raise_delivery_errors = false

  # Make template changes take effect immediately.
  config.action_mailer.perform_caching = false

  # Set localhost to be used by links generated in mailer templates.
  config.action_mailer.default_url_options = { host: "localhost", port: 3004 }

  # Print deprecation notices to the Rails logger.
  config.active_support.deprecation = :log

  # Raise an error on page load if there are pending migrations.
  config.active_record.migration_error = :page_load

  # Highlight code that triggered database queries in logs.
  config.active_record.verbose_query_logs = true

  # Append comments with runtime information tags to SQL queries in logs.
  config.active_record.query_log_tags_enabled = true

  # Highlight code that enqueued background job in logs.
  config.active_job.verbose_enqueue_logs = true

  # Use Sidekiq for background jobs.
  config.active_job.queue_adapter = :sidekiq

  # Highlight code that triggered redirect in logs.
  config.action_dispatch.verbose_redirect_logs = true

  # Raises error for missing translations.
  # config.i18n.raise_on_missing_translations = true

  # Annotate rendered view with file names.
  config.action_view.annotate_rendered_view_with_filenames = true

  # Allow localtunnel connections (*.loca.lt)
  config.hosts << ".loca.lt"

  # Allow Action Cable from localtunnel origins
  config.action_cable.allowed_request_origins = [
    %r{https?://.*\.loca\.lt},
    %r{https?://localhost(:\d+)?}
  ]

  # Raise error when a before_action's only/except options reference missing actions.
  config.action_controller.raise_on_missing_callback_actions = true

  # Apply autocorrection by RuboCop to files generated by `bin/rails generate`.
  # config.generators.apply_rubocop_autocorrect_after_generate!
end
